-- ================================ Function(V5.1.7) ================================
/* reverse-反转 321 */
SELECT reverse(123);

/* hash-哈希值: 3904355907 */
SELECT crc32("a")

/* floor-取整: 3 */
SELECT floor(3.2)

/* rand-随机小数: 0-1 */
SELECT rand();

/* month-取出月份: 8 */
SELECT now()

/* now()-当前日期 */
SELECT MONTH('2018-08-01')

/* convert-转换成mb4 */
CONVERT("TEST" USING UTF8MB4);

/* sleep(2)-睡眠2秒 */
SELECT sleep(2);

/*  */
/*  */


